### PR TITLE
Readme nitpicking

### PR DESCRIPTION
**Pull request by wokalski**
- GitHub markdown was slightly changed
- I had to reread the section with `cur` a few times until I understood that it meant `current`

### CODE REVIEW

**Comment by jordwalke** [comment]
There are some variables like `cur__root`, `cur__lib` though. Maybe just write it like `cur(current)`

**Comment by wokalski** [comment]
Consistency is very important. I'll write 

> `cur` (current) package

The first time `cur` is mentioned and other references will just be `cur`.

**Comment by jordwalke** [comment]
Sounds good.

**Comment by wokalski** [comment]
Done.

**Comment by jordwalke** [comment]
Btw, hate to do this to ya, but the repo has moved [here](https://github.com/reasonml/esy) (and we only use this repo for issues).

**Comment by wokalski** [comment]
I know. But i found the documentation valuable for my understanding of esy. Maybe someone else will too.

**Comment by jordwalke** [comment]
Okay, I'll move these docs (along with your changes) (anything that isn't already in the official yarn fork repo already) over to the yarn fork repo. Just to make sure it's all in one place.

**Pull request merged**
