### PR TITLE
My work on Esy

### PR DESCRIPTION
**Pull request by SanderSpies**
[Obligatory: do not merge]

This is a work in progress, I still need to combine it with your existing work.

I like to know if you agree or disagree with the direction that I'm taking.

### CODE REVIEW

**Comment by SanderSpies** [comment]
This is an example output of my local test structure:

```
{ name: 'yolo',
  build: undefined,
  version: '0.0.1',
  exportedEnvVars: 
   [ { key: 'Foo', scope: [ 'local' ], value: 'bar' },
     { key: 'Bar', scope: [ 'global' ], value: 'test' } ],
  runtimeEnvVars: 
   [ { key: 'Foo', scope: [ 'local' ], value: 'bar' },
     { key: 'Foo2', scope: [ 'export' ], value: 'exportedValue' },
     { key: 'YOLO', scope: [ 'export' ], value: 'lolwut' },
     { key: 'DEEP', scope: [ 'global', 'local' ], value: 'xxx' } ],
  dependencies: null,
  deps: 
   [ { name: 'Z',
       build: undefined,
       version: '0.0.1',
       exportedEnvVars: 
        [ { key: 'Foo2', scope: [ 'export' ], value: 'exportedValue' },
          { key: 'Bar2', scope: [ 'local' ], value: 'test' } ],
       runtimeEnvVars: 
        [ { key: 'Bar2', scope: [ 'local' ], value: 'test' },
          { key: 'DEEP', scope: [ 'global', 'local' ], value: 'xxx' } ],
       dependencies: null,
       deps: 
        [ { name: 'B',
            build: undefined,
            version: '0.0.1',
            exportedEnvVars: [ { key: 'DEEP', scope: [ 'global', 'local' ], value: 'xxx' } ],
            runtimeEnvVars: [ { key: 'DEEP', scope: [ 'global', 'local' ], value: 'xxx' } ],
            dependencies: undefined,
            deps: [] } ] },
     { name: 'B',
       build: undefined,
       version: '0.0.1',
       exportedEnvVars: [ { key: 'YOLO', scope: [ 'export' ], value: 'lolwut' } ],
       runtimeEnvVars: [],
       dependencies: undefined,
       deps: [] } ] }
```

(Updated Nov. 12)

**Comment by SanderSpies** [comment]
So the `exportedEnvVars` are the ones that the user has entered, but transformed in a more easy to use array for processing.

And the `runtimeEnvVars` are the variables that will be actually set during runtime.

**Comment by jordwalke** [comment]
So where would the current esyEnv script fit in?
And is the idea that we take this output you are showing and then either turn it into a makefile or execute it in node directly?

**Comment by jordwalke** [comment]
I think that runtime env vars is just the thing that esyEnv computes for each package in the build process. Maybe we think of a different name than runtime though.

**Comment by SanderSpies** [comment]
[Updated Nov 27]

And now it generates the contents for a simple makefile, like this: 
```
C
	# Built-in environment variables
	export C_name=C
	export C_version=0.0.1
	export C__target_dir=.
	export C__install=_install/
	export C__root=sandbox/
	export C__depends=[]
	export C__bin=sandbox/C/bin
	export C__sbin=sandbox/C/sbin
	export C__lib=sandbox/C/lib
	export C__man=sandbox/C/man
	export C__doc=sandbox/C/doc
	export C__stublibs=sandbox/C/stublibs
	export C__toplevel=sandbox/C/toplevel
	export C__share=sandbox/C/share
	export C__etc=sandbox/C/etc

	# Exported environment variabless
	export C__DEEP____esy_scope__1480254203179=xxx

	# Environment variables coming from dependencies
	export DEEP=$C__DEEP____esy_scope__1480254203179

	# Build command
	./z1

	# Reset imported environment variables
	unset DEEP

Z : C
	# Built-in environment variables
	export Z_name=Z
	export Z_version=0.0.1
	export Z__target_dir=.
	export Z__install=_install/
	export Z__root=sandbox/
	export Z__depends=[C]
	export Z__bin=sandbox/Z/bin
	export Z__sbin=sandbox/Z/sbin
	export Z__lib=sandbox/Z/lib
	export Z__man=sandbox/Z/man
	export Z__doc=sandbox/Z/doc
	export Z__stublibs=sandbox/Z/stublibs
	export Z__toplevel=sandbox/Z/toplevel
	export Z__share=sandbox/Z/share
	export Z__etc=sandbox/Z/etc

	# Exported environment variabless
	export Z__Foo2____esy_scope__1480254203179=$DEEP
	export Z__Bar2____esy_scope__1480254203179=test

	# Environment variables coming from dependencies
	export Bar2=$Z__Bar2____esy_scope__1480254203179
	export DEEP=$C__DEEP____esy_scope__1480254203179

	# Build command
	./abc1

	# Reset imported environment variables
	unset Bar2
	unset DEEP

B
	# Built-in environment variables
	export B_name=B
	export B_version=0.0.1
	export B__target_dir=.
	export B__install=_install/
	export B__root=sandbox/
	export B__depends=[]
	export B__bin=sandbox/B/bin
	export B__sbin=sandbox/B/sbin
	export B__lib=sandbox/B/lib
	export B__man=sandbox/B/man
	export B__doc=sandbox/B/doc
	export B__stublibs=sandbox/B/stublibs
	export B__toplevel=sandbox/B/toplevel
	export B__share=sandbox/B/share
	export B__etc=sandbox/B/etc

	# Exported environment variabless
	export B__YOLO____esy_scope__1480254203179=lolwut

	# Build command
	./def1

yolo : Z B
	# Built-in environment variables
	export yolo_name=yolo
	export yolo_version=0.0.1
	export yolo__target_dir=.
	export yolo__install=_install/
	export yolo__root=sandbox/
	export yolo__depends=[Z,B]
	export yolo__bin=sandbox/yolo/bin
	export yolo__sbin=sandbox/yolo/sbin
	export yolo__lib=sandbox/yolo/lib
	export yolo__man=sandbox/yolo/man
	export yolo__doc=sandbox/yolo/doc
	export yolo__stublibs=sandbox/yolo/stublibs
	export yolo__toplevel=sandbox/yolo/toplevel
	export yolo__share=sandbox/yolo/share
	export yolo__etc=sandbox/yolo/etc

	# Exported environment variabless
	export yolo__Foo____esy_scope__1480254203179=bar
	export yolo__Bar____esy_scope__1480254203179=test

	# Environment variables coming from dependencies
	export Foo=$yolo__Foo____esy_scope__1480254203179
	export Foo2=$Z__Foo2____esy_scope__1480254203179
	export YOLO=$B__YOLO____esy_scope__1480254203179
	export DEEP=$C__DEEP____esy_scope__1480254203179

	# Build command
	./stuff

	# Reset imported environment variables
	unset Foo
	unset Foo2
	unset YOLO
	unset DEEP

	#TODO: Reset all other variables

default: yolo
```

from this input (which in turn is generated from the package.json files):

```
{ name: 'yolo',
  build: 'stuff',
  version: '0.0.1',
  exportedEnvVars: 
   [ { key: 'Foo', scope: [ 'local' ], value: 'bar' },
     { key: 'Bar', scope: [ 'global' ], value: 'test' } ],
  runtimeEnvVars: 
   [ { key: 'Foo', scope: [ 'local' ], value: 'bar' },
     { key: 'Foo2', scope: [ 'export' ], value: 'exportedValue' },
     { key: 'YOLO', scope: [ 'export' ], value: 'lolwut' },
     { key: 'DEEP', scope: [ 'global', 'local' ], value: 'xxx' } ],
  dependencies: { A: '', B: '' },
  deps: 
   [ { name: 'Z',
       build: 'abc1',
       version: '0.0.1',
       exportedEnvVars: 
        [ { key: 'Foo2', scope: [ 'export' ], value: 'exportedValue' },
          { key: 'Bar2', scope: [ 'local' ], value: 'test' } ],
       runtimeEnvVars: 
        [ { key: 'Bar2', scope: [ 'local' ], value: 'test' },
          { key: 'DEEP', scope: [ 'global', 'local' ], value: 'xxx' } ],
       dependencies: { C: '' },
       deps: 
        [ { name: 'C',
            build: 'z1',
            version: '0.0.1',
            exportedEnvVars: [ { key: 'DEEP', scope: [ 'global', 'local' ], value: 'xxx' } ],
            runtimeEnvVars: [ { key: 'DEEP', scope: [ 'global', 'local' ], value: 'xxx' } ],
            dependencies: undefined,
            deps: [] } ] },
     { name: 'B',
       build: 'def1',
       version: '0.0.1',
       exportedEnvVars: [ { key: 'YOLO', scope: [ 'export' ], value: 'lolwut' } ],
       runtimeEnvVars: [],
       dependencies: undefined,
       deps: [] } ] }
```

**Comment by jordwalke** [comment]
Very cool! Looks like it's on the right track.

**Comment by jordwalke** [comment]
Does this supersede the `esyEnv` that I built? Do you somehow make use of it? The work done in `esyEnv.js` allows packages like `Z` to see some of the env vars defined by `C`. (only under the right conditions).

**Comment by SanderSpies** [comment]
Eventually yes, but it's missing the validation part right now. And then some more, just haven't had really the time to properly hack on this. 

The behaviour seems similar to what my runtime env vars do.

**Comment by SanderSpies** [comment]
The scoping is now working correctly which wasn't the case before. I'm obfuscating the names of exported variables and de-obfuscate them at the usage location. And unsetting them when they are not needed anymore.

**Comment by SanderSpies** [comment]
Closing in favour of @andreypopp's work.

**Pull request closed without merging**
